### ISSUE TITLE
Is there an update plan for the latest version?

### ISSUE THREAD

**Issue by haoxinllc** [Mafalda-SFU/Mafalda-SFU.github.io#1]
Is your Packages (Mafalda sub-projects) Roadmap still in progress, any code updates in the near future?

**Comment by piranna** [comment]
hi @haoxinllc, I'm still on development and trying to stick to my roadmap, but also I'm busy with work. Is there any feature you are interested about? Maybe we can talk over email, you can write me at jesus.leganes.combarro@gmail.com.

**Comment by piranna** [comment]
Closed due to lack of response. If you have any other question, don't doubt re-opening the issue.
